### ISSUE TITLE
Creating schema for poll info

### ISSUE THREAD

**Issue by dakshgupta2002** [agamjotsingh18/pollitup#19] opened 2022-02-18 03:13 UTC
Making a schema for polls including: 
Title, description, upvotes, downvotes, timestamps
using mongoose ODM

**Comment by agamjotsingh18** [comment] 2022-02-19 05:32
Sure to on @dakshgupta2002

**Comment by Gurdeep475** [comment] 2022-02-27 12:34
if the issue is still open, please assign it to me. I want to work under GSSOC`22.

**Closed** 2022-02-27 16:13 UTC
Labels: enhancement, good first issue, Easy, JWOC
