### ISSUE TITLE
Setting up backend folder structure 

### ISSUE THREAD

**Issue by dakshgupta2002** [agamjotsingh18/pollitup#18] opened 2022-02-18 03:13 UTC
Setting the backend as Model, Router and Controller folder structure

**Comment by agamjotsingh18** [comment] 2022-02-19 05:33
Sure you can work

**Comment by Gurdeep475** [comment] 2022-02-27 12:34
if the issue is still open, please assign it to me. I would like to work on it under GSSOC`22.

**Closed** 2022-02-27 15:04 UTC
Labels: good first issue, Easy, JWOC
